// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServidorApi.Data;

#nullable disable

namespace ServidorApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260319170044_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("ServidorApi.Models.Articulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Articulos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Imagen = "/fotos/Aceite de oliva virgen extra 1L 779.png",
                            Nombre = "Aceite de oliva virgen extra 1L",
                            Precio = 7.79m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 2,
                            Imagen = "/fotos/Agua mineral 1,5L 075.png",
                            Nombre = "Agua mineral 1,5L",
                            Precio = 0.75m,
                            Stock = 120
                        },
                        new
                        {
                            Id = 3,
                            Imagen = "/fotos/Arroz redondo 1kg 195.png",
                            Nombre = "Arroz redondo 1kg",
                            Precio = 1.95m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 4,
                            Imagen = "/fotos/Azúcar blanco 1kg 150.png",
                            Nombre = "Azúcar blanco 1kg",
                            Precio = 1.50m,
                            Stock = 70
                        },
                        new
                        {
                            Id = 5,
                            Imagen = "/fotos/Barra de pan 075.png",
                            Nombre = "Barra de pan",
                            Precio = 0.75m,
                            Stock = 150
                        },
                        new
                        {
                            Id = 6,
                            Imagen = "/fotos/Carne picada mixta 500g 520.png",
                            Nombre = "Carne picada mixta 500g",
                            Precio = 5.20m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 7,
                            Imagen = "/fotos/Chocolate con leche 100g 299.png",
                            Nombre = "Chocolate con leche 100g",
                            Precio = 2.00m,
                            Stock = 46
                        },
                        new
                        {
                            Id = 8,
                            Imagen = "/fotos/Detergente líquido 2L 1420.png",
                            Nombre = "Detergente líquido 2L",
                            Precio = 14.20m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 9,
                            Imagen = "/fotos/Galletas María 100.png",
                            Nombre = "Galletas María",
                            Precio = 1.00m,
                            Stock = 90
                        },
                        new
                        {
                            Id = 10,
                            Imagen = "/fotos/Helado de vainilla 1L 412.png",
                            Nombre = "Helado de vainilla 1L",
                            Precio = 4.12m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 11,
                            Imagen = "/fotos/Huevos camperos (12u) 419.png",
                            Nombre = "Huevos camperos (12u)",
                            Precio = 4.19m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 12,
                            Imagen = "/fotos/Leche semidesnatada 1L 135.png",
                            Nombre = "Leche semidesnatada 1L",
                            Precio = 1.35m,
                            Stock = 110
                        },
                        new
                        {
                            Id = 13,
                            Imagen = "/fotos/Leche sin lactosa 1L 155.png",
                            Nombre = "Leche sin lactosa 1L",
                            Precio = 1.55m,
                            Stock = 90
                        },
                        new
                        {
                            Id = 14,
                            Imagen = "/fotos/Lechuga iceberg 130.png",
                            Nombre = "Lechuga iceberg",
                            Precio = 1.30m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 15,
                            Imagen = "/fotos/Lentejas pardinas 1kg 350.png",
                            Nombre = "Lentejas pardinas 1kg",
                            Precio = 3.50m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 16,
                            Imagen = "/fotos/Manzanas Golden 1kg 199.png",
                            Nombre = "Manzanas Golden 1kg",
                            Precio = 1.99m,
                            Stock = 70
                        },
                        new
                        {
                            Id = 17,
                            Imagen = "/fotos/Naranjas 1kg 225.png",
                            Nombre = "Naranjas 1kg",
                            Precio = 2.25m,
                            Stock = 65
                        },
                        new
                        {
                            Id = 18,
                            Imagen = "/fotos/Pan de molde integral 135.png",
                            Nombre = "Pan de molde integral",
                            Precio = 1.35m,
                            Stock = 55
                        },
                        new
                        {
                            Id = 19,
                            Imagen = "/fotos/Papel higiénico (12 rollos) 715.png",
                            Nombre = "Papel higiénico (12 rollos)",
                            Precio = 7.15m,
                            Stock = 45
                        },
                        new
                        {
                            Id = 20,
                            Imagen = "/fotos/Pasta espaguetis 1kg 120.png",
                            Nombre = "Pasta espaguetis 1kg",
                            Precio = 1.20m,
                            Stock = 85
                        },
                        new
                        {
                            Id = 21,
                            Imagen = "/fotos/Pechuga de pollo 1kg 649.png",
                            Nombre = "Pechuga de pollo 1kg",
                            Precio = 6.49m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 22,
                            Imagen = "/fotos/Pizza congelada 4 quesos 395.png",
                            Nombre = "Pizza congelada 4 quesos",
                            Precio = 3.95m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 23,
                            Imagen = "/fotos/Plátanos 1kg Canarias 292.png",
                            Nombre = "Plátanos 1kg Canarias",
                            Precio = 2.92m,
                            Stock = 75
                        },
                        new
                        {
                            Id = 24,
                            Imagen = "/fotos/Refresco de cola 2L 215.png",
                            Nombre = "Refresco de cola 2L",
                            Precio = 2.15m,
                            Stock = 95
                        },
                        new
                        {
                            Id = 25,
                            Imagen = "/fotos/Sal fina 1kg 040.png",
                            Nombre = "Sal fina 1kg",
                            Precio = 0.40m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 26,
                            Imagen = "/fotos/Tomates pera 1kg 144.png",
                            Nombre = "Tomates pera 1kg",
                            Precio = 1.44m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 27,
                            Imagen = "/fotos/Vinagre de vino 500ml 079.png",
                            Nombre = "Vinagre de vino 500ml",
                            Precio = 0.79m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 28,
                            Imagen = "/fotos/Yogur proteico de fresa 199.png",
                            Nombre = "Yogur proteico de fresa",
                            Precio = 1.99m,
                            Stock = 70
                        },
                        new
                        {
                            Id = 29,
                            Imagen = "/fotos/Yogur proteico natural 199.png",
                            Nombre = "Yogur proteico natural",
                            Precio = 1.99m,
                            Stock = 70
                        },
                        new
                        {
                            Id = 30,
                            Imagen = "/fotos/Zanahorias 1kg 135.png",
                            Nombre = "Zanahorias 1kg",
                            Precio = 1.35m,
                            Stock = 85
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
